baseURL: https://www.theobeers.com/ajam-session/
languageCode: en-us
title: ‘ajam session
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  description:
    "A workshop on premodern literary exchange between Persian and Arabic"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set

  # home-info mode
  homeInfoParams:
    title:
      "A workshop on premodern literary exchange between Persian and Arabic"
    content: "To be held at the Freie Universität Berlin, 27--28 October 2022"

  socialIcons:
    - name: github
      url: "https://github.com/theodore-s-beers/ajam-session"
    - name: twitter
      url: "https://twitter.com/theodorebeers"

  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: participants
      name: participants
      url: /participants/
      weight: 20
